on: 
  push:
    branches: 
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: jorisxl2.two.axc.nl
        FTP_USERNAME: omloop@omloopdesnor.nl
        FTP_PASSWORD: ${{ secrets.ftppassword }}
        ARGS: --exclude-glob=.git*/** --exclude-glob=.git** --exclude=readme.md 
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Pin-IPFS
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: alexanderschau/ipfs-pinning-action@v1.0.0
      with:
        path_to_add: '/.github/' #Required
        endpoint: ${{ secrets.ENDPOINT }} #Required
        access_token: ${{ secrets.ACCESS_TOKEN }} #Required
        pin_name: 'ODS-GitHub-PIN' #Optional
        
